### ISSUE TITLE
Helping to fix apple services. 

### ISSUE THREAD

**Issue by devboloji** [ParrotXray/Asus-laptop-X415jp-Hackintosh#1]
I faced issue with iservices before, it can be fixed the problem by [DRIVE link](https://drive.google.com/file/d/1GrN5ncAy79MO4ssXQ8STQXheDwjPYvOU/view?usp=drivesdk) and add this aml to ACPI. Let me know whether it's working or not..

**Comment by ParrotXray** [comment]
> I faced issue with iservices before, it can be fixed the problem by [DRIVE link](https://drive.google.com/file/d/1GrN5ncAy79MO4ssXQ8STQXheDwjPYvOU/view?usp=drivesdk) and add this aml to ACPI. Let me know whether it's working or not..

I will try this
Can I solve the problem of no sound after restarting from Windows to macOS, thank you

**Comment by devboloji** [comment]
@ParrotXray did you mapped usb and stuff?
